version: '3'

services:
  service-db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./scripts/postgresql/init_api_db.sql:/docker-entrypoint-initdb.d/init_api_db.sql
    networks:
      - service-network

  balance-service:
    depends_on:
      - service-db
    image: tullerpeton/balance-service:v1.0
    container_name: balance_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./configs/app:/configs/app
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
